### ISSUE TITLE
Does not parse regex correctly

### ISSUE THREAD

**Issue by dafsu** [spohara79/snort_rules#1]
Problem:
A rule containing something like this: pcre:"/\/\?[a-f0-9]{64}\;\d\;\d/U";
Will be parsed to this: ('pcre', '"/\\/\\?[a-f0-9]{64}\\')

**Comment by dafsu** [comment]
This regex should solve the issue:
```python
(\w+):\"([^\"]*?)\";|(\w+);|(\w+):(.*?);
```

**Comment by spohara79** [comment]
Thanks.  Updated.

**Comment by dafsu** [comment]
It migth be needed to add the following as well:


```python

        new_matches = []
        for i in matches:
            tmp = []
            for j in i:
                if not j == '':
                    tmp.append(j)
            if len(tmp) == 1:
                tmp = ['','',tmp[0]]
            elif len(tmp) == 2:
                tmp.append('')
            new_matches.append(tmp)
        matches = new_matches
```

But maybe some testing can reveal something

________________________________
Fra: Sean <notifications@github.com>
Sendt: 27. november 2019 15:50:29
Til: spohara79/snort_rules
Cc: David Askirk Fotel; Author
Emne: Re: [spohara79/snort_rules] Does not parse regex correctly (#1)


Thanks. Updated.
